# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/tyk-front

hooks:
  AfterInstall:
    - location: scripts/install_deps.sh
      runas: root
    - location: scripts/build_app.sh
      runas: root
  ApplicationStart:
    - location: scripts/restart_services.sh
      runas: root
